config:
    include:
        - "share/zprime/default_train/high_mass/input.yaml"

job:
    job_name: "tune-high-mass"
    job_type: "tune"
    save_dir: "run/zprime/test"

tune:
    tuner:
        scheduler_class: AsyncHyperBandScheduler
        scheduler:
            time_attr: training_iteration
            max_t: 10
            grace_period: 3
        algo_class: HEBOSearch
        algo:
            metric: val_auc
            mode: max
        run:
            metric: val_auc
            mode: max
            #stop:
            #val_accuracy: 0.99
            #training_iteration: 3
            num_samples: 8
            resources_per_trial:
                cpu: 1
                gpu: 0
            log_to_file: true
            #verbose: 2
    model_class: "Model_Sequential_Flat"
    model:
        layers:
            spacer: choice
            paras:
                categories: [2, 3, 4, 5, 6, 7, 8]
        nodes:
            spacer: choice
            paras:
                categories: [16, 32, 64, 128, 256]
        dropout_rate: 0
        momentum: 0.5
        nesterov: true
        test_rate: .2
        val_split: .25
        learn_rate:
            spacer: qloguniform
            paras:
                lower: 1.e-5
                upper: 1
                q: 1.e-5
        learn_rate_decay:
            spacer: qloguniform
            paras:
                lower: 1.e-5
                upper: 0.01
                q: 5.e-6
        batch_size: 128
        epochs: 100
        sig_class_weight:
            spacer: quniform
            paras:
                lower: 1
                upper: 10
                q: 1
        bkg_class_weight:
            spacer: quniform
            paras:
                lower: 1
                upper: 20
                q: 1
        use_early_stop: true
        early_stop_paras:
            monitor: "val_auc"
            min_delta: 0.0005
            patience: 1
            mode: "max"
            restore_best_weights: true
