config:
    include:
        - "share/lfv/emu/prepare_debug.yaml"

job:
    job_name: "emu-pnn-test"
    job_type: "train"
    load_job_name: "emu-pnn-test"
    save_dir: "run/test/emu"
    rdm_seed: 91

train:
    model_name: "lfv_emu"
    model_class: "Model_Sequential_Flat"
    layers: 5
    nodes: 128
    dropout_rate: 0
    momentum: 0.8
    nesterov: true
    test_rate: .2
    val_split: .25
    #k_folds: 5
    learn_rate: 0.003
    #learn_rate_decay: 1.e-4
    learn_rate_decay: 1.e-5
    batch_size: 64
    epochs: 100
    sig_class_weight: 3.
    bkg_class_weight: 1.
    # early stop setups
    use_early_stop: true
    early_stop_paras:
        monitor: "val_loss"
        min_delta: 0
        patience: 3
        mode: "min"
        restore_best_weights: true

    verbose: 1
