config:
    include:
        - "share/zprime/eb-simpler-dnn/high_mass/input.yaml"
        - "share/zprime/eb-simpler-dnn/high_mass/train.yaml"

job:
    job_name: "train-layers-05-nodes-064"
    job_type: "train"
    save_dir: "run/zprime/eb-simple-dnn/high_mass"

train:
    layers: 5
    nodes: 64
