config:
    include:
        - "share/lfv/input/input_etau_qbh_n1.sec.yaml"
        - "share/lfv/train/train_etau_qbh_n1.sec.yaml"

job:
    job_name: "train_qbh_n1"
    job_type: "train"
    save_dir: "run/lfv/default/etau"
