config:
    include:
        - "share/zprime/input/input_hm.sec.yaml"
        - "share/zprime/train/train_hm.sec.yaml"
    #best_tune_overwrite: True

job:
    job_name: "train-best-limit"
    job_type: "train"
    save_dir: "run/zprime/default_train/high_mass"

input:
    bkg_sumofweight: 1906250
    sig_sumofweight: 103972
