config:
    include:
        - "share/zprime/default_train/high_mass/input.yaml"
    best_tune_overwrite: True

#input:
    # cut_expression: "mz1 > 35 & mz1 < 80"

job:
    job_name: "train-all-mass-best"
    job_type: "train"
    tune_job_name: "tune-high-mass"
    save_dir: "run/zprime/test"

train:
    model_name: "zprime_pdnn_model"
    model_class: "Model_Sequential_Flat"
    layers: 2
    nodes: 64
    dropout_rate: 0
    momentum: 0.5
    nesterov: true
    test_rate: .2
    val_split: .25
    learn_rate: 0.0115156
    learn_rate_decay: 0.00710462
    batch_size: 1024
    epochs: 50
    sig_class_weight: 2.17531
    bkg_class_weight: 15.842
    train_metrics_weighted:
        - "accuracy"
        - "auc"
    # early stop setups
    use_early_stop: false
    early_stop_paras:
        monitor: "val_auc"
        min_delta: 0.0005
        patience: 1
        mode: "max"
        restore_best_weights: true
    # save model or not
    save_model: true

    verbose: 1
