# currently, using hyperparameters optimized on limit@75GeV

config:
    include:
        - "share/zprime/input/input_hm.sec.yaml"
        - "share/zprime/train/train_hm.sec.yaml"

job:
    job_name: "train_no_m_57"
    job_type: "train"
    save_dir: "run/zprime/eb_checks_2022/high_mass"

input:
    bkg_sumofweight: 1906250
    sig_sumofweight: 103972

    sig_list:
        - "sig_Zp042"
        - "sig_Zp045"
        - "sig_Zp048"
        - "sig_Zp051"
        - "sig_Zp054"
        #- "sig_Zp057"
        - "sig_Zp060"
        - "sig_Zp063"
        - "sig_Zp066"
        - "sig_Zp069"
        - "sig_Zp072"
        - "sig_Zp075"